global:
  scrape_interval: 15s  # Intervalo padrão de coleta de métricas para todos os jobs

scrape_configs:
  - job_name: 'prometheus'  # Nome do job para o Prometheus
    static_configs:
      - targets: ['172.18.0.5:9090']  # Definição do alvo, neste caso o próprio Prometheus

  - job_name: 'mysqld_exporter'  # Nome do job para o MySQL Exporter
    static_configs:
      - targets: ['172.18.0.3:9104']  # Definição do alvo para coletar métricas do MySQL Exporter

