{
 "title": "Monitoramento Acessos e Consultas",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Número de Acessos",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total[5m]))",
     "legendFormat": "Acessos por segundo"
    }
   ]
  },
  {
   "title": "Consultas ao Banco de Dados",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(db_queries_total[5m]))",
     "legendFormat": "Consultas por segundo"
    }
   ]
  },
  {
   "title": "Uso de CPU",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "CPU (%)"
    }
   ]
  },
  {
   "title": "Tempo de Resposta",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m]))",
     "legendFormat": "95th Percentile"
    }
   ]
  }
 ]
}